### ISSUE TITLE
OFL?

### ISSUE THREAD

**Issue by davelab6** [alif-type/punk-otf#1]
Can this be OFL?

**Comment by khaledhosny** [comment]
I don’t know, can I just slap an OFL on top of Knuth’s license?

**Comment by davelab6** [comment]
Well it says,

```
"Unlimited copying and redistribution of this file are permitted as long
  as this file is not modified. Modifications are permitted, but only if
  the resulting file is not named 'punknova.otf' and the (internal)
  fontname differs from 'Punk Nova'."
```

What exactly is "this file"?

**Comment by khaledhosny** [comment]
I don’t even remember. Checking the repository history…

**Comment by khaledhosny** [comment]
It was referring to the OTF files. I think it was Hans idea, since this is a very TeX thing. I switched to OFL.
